### ISSUE TITLE
Add option '--include-if-has-file=the-given-file' to allow file based inclusion

### ISSUE THREAD

**Issue by ochorocho** [mborne/satis-gitlab#20]
I would be nice to have a option to include only specific project in case it contains a certain file, e.g. `.satisinclude`.

We have a bunch of projects that are not supposed to show up in satis. For our company it makes more sense to include specific projects when a cetain files exists.

**Comment by mborne** [comment]
Hello,

I have to introduce a kind of "ProjectFilterInterface" to simplify this kind of customization.

Then, is it ok for you if I introduce a `--include-if-has-file=.satisinclude` option instead of yours?

**Comment by ochorocho** [comment]
Hey, as long as it does the same job i'm happy with it. :-)

thank you.
