### ISSUE TITLE
Fail if API is not available

### ISSUE THREAD

**Issue by ochorocho** [mborne/satis-gitlab#28]
Hey,

 we are running `satis-gitlab` in a gitlab-ci job.
It would be great to have an option e.g. `--ignore-api-failures=0` to let gitlabs build process fail when the api is not available.

Long story short, throw an exception in case things went south ;-)

![bildschirmfoto 2018-10-25 um 07 24 27](https://user-images.githubusercontent.com/4623070/47477810-53706880-d827-11e8-88ae-ce8e768bcc72.png)

**Comment by mborne** [comment]
Hello,

I don't understand the problem. Exceptions are already thrown so that something like this should work : 

```bash
#!/bin/bash
bin/satis-gitlab gitlab-to-config $GITLAB_URL $GITLAB_TOKEN | { exit 1; }
bin/satis-gitlab build --skip-errors satis.json web
```

**Comment by ochorocho** [comment]
Ah ok ... thanks. This seems to work for me now.

**Comment by mborne** [comment]
Sorry for the month to get an answer :)

Tel me if you face problems with the master branch : 
- support for github have been added with orgs/groups and user filtering
- git client have been moved out and published on packagist
