### ISSUE TITLE
Build sucess generate a FATAL

### ISSUE THREAD

**Issue by MaximeCulea** [mborne/satis-gitlab#38]
Hello,

I have an issue on building config.json, it happens here https://github.com/mborne/satis-gitlab/blob/master/src/MBO/SatisGitlab/Command/GitlabToConfigCommand.php#L298

Here is the output:
`PHP Fatal error:  Uncaught Error: Undefined class constant 'SUCCESS' in /var/www/satis/src/MBO/SatisGitlab/Command/GitlabToConfigCommand.php:298
Stack trace:
#0 /var/www/satis/vendor/symfony/console/Command/Command.php(255): MBO\SatisGitlab\Command\GitlabToConfigCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/satis/vendor/symfony/console/Application.php(992): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/satis/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(MBO\SatisGitlab\Command\GitlabToConfigCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/satis/vendor/composer/satis/src/Console/Application.php(54): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\Argv in /var/www/satis/src/MBO/SatisGitlab/Command/GitlabToConfigCommand.php on line 298`

I might think that command static success var doesn't exist anymore
Returning 0 works.
Thank you

**Comment by mborne** [comment]
Hello @MaximeCulea ,

This error is a bit strange. Meanwhile, [following Symfony's doc](https://symfony.com/doc/current/console.html#creating-a-command) and returning `Command::SUCCESS` instead of `static::SUCCESS` should fix it in v0.3.0
